pipeline:
  build:
    image: golang:latest
    commands:
      - export PATH=$PATH:$(go env GOPATH)/bin
      - export GOPATH=$(go env GOPATH)
      - go get
      - go build
      - go test

  publish:
    image: plugins/docker
    repo: 192.168.10.250:4443/jberghoef/gocdn
    tags: [ latest ]
    registry: 192.168.10.250:4443
